---
development:
  # Infrastructure
  API_HOST: http://localhost:9292

test:
  # Infrastructure
  API_HOST: http://localhost:9090

app_test:
  # Application
  APP_HOST: http://localhost:9000
  API_HOST: http://localhost:9090

production:
  # Infrastructure
  API_HOST: https://pokezon-api.herokuapp.com